using System.Linq;
using System.Collections.Generic;
using Bank4Us.Core;

namespace Bank4Us.Core.Tests;

/*
 AltWalker is an open‑source Model‑Based Testing (MBT) framework that allows you to
 write automated tests in .NET/C# or Python, and execute those tests based on
 paths generated from a behavioral model. It is designed specifically to support
 MBT workflows where models are represented as directed graphs (states + transitions).

 This test demonstrates how generated sequences (from a model-based tester such
 as AltWalker or the local adapter) can be executed against `AccountApplication`
 to validate state transitions and verification combinations.
*/
public class ModelBasedTesterTests
{
    [Fact]
    public void GeneratedSequences_CoverSubmittedAndVerificationCombos()
    {
        var sequences = AltWalkerAdapter.GenerateSequences(ApplicationStatus.Started, maxDepth: 10).ToList();
        // Ensure some sequences were generated
        Assert.True(sequences.Count > 0, "No sequences generated by the model-based tester");

        // Find sequences that reach the Submitted state and end with SubmitApplication
        var submittedSeqs = sequences.Where(s => s.Contains("SubmitApplication") && s.Last() == "SubmitApplication").ToList();
        Assert.True(submittedSeqs.Count > 0, "No sequences reach Submitted state");

        // Execute each submitted sequence then append verification combos and assert final states
        foreach (var baseSeq in submittedSeqs)
        {
            // try all verification combinations
            foreach (var combo in new[] { new[] { true, true, true }, new[] { true, true, false }, new[] { false, true, true }, new[] { true, false, true } })
            {
                var app = new AccountApplication();
                AltWalkerAdapter.ExecuteSequence(app, baseSeq);

                // Append verifications according to combo
                var verificationSteps = new List<string>
                {
                    combo[0] ? "VerifyId_Success" : "VerifyId_Failure",
                    combo[1] ? "VerifyAddress_Success" : "VerifyAddress_Failure",
                    combo[2] ? "VerifyCitizen_Success" : "VerifyCitizen_Failure",
                };

                AltWalkerAdapter.ExecuteSequence(app, verificationSteps);

                var expected = (combo[0] && combo[1] && combo[2]) ? ApplicationStatus.Approved : ApplicationStatus.Rejected;
                Assert.Equal(expected, app.Status);
            }
        }
    }

    [Fact]
    public void AltWalkerModel_IsLoadedCorrectly()
    {
        // Verify that the AltWalker JSON model can be loaded
        var model = AltWalkerAdapter.GetLoadedModel();
        Assert.NotNull(model);
        Assert.NotEmpty(model.models);

        var modelDef = model.models.First();
        Assert.Equal("Bank4UsAccountOpening", modelDef.name);
        Assert.Equal("random", modelDef.generator);
        Assert.Equal("Started", modelDef.startElementId);

        // Verify vertices
        Assert.Equal(11, modelDef.vertices.Count);
        var vertexNames = modelDef.vertices.Select(v => v.name).ToList();
        Assert.Contains("Started", vertexNames);
        Assert.Contains("Approved", vertexNames);
        Assert.Contains("Rejected", vertexNames);

        // Verify edges
        Assert.Equal(13, modelDef.edges.Count);
        var edgeNames = modelDef.edges.Select(e => e.name).ToList();
        Assert.Contains("ProvidePersonalDetails", edgeNames);
        Assert.Contains("SubmitApplication", edgeNames);
        Assert.Contains("VerifyId_Success", edgeNames);
        Assert.Contains("VerifyId_Failure", edgeNames);
    }

    [Fact]
    public void AltWalkerModel_StructureMatchesImplementation()
    {
        // Verify that the model structure matches the AccountApplication implementation
        var model = AltWalkerAdapter.GetLoadedModel();
        Assert.NotNull(model);

        var modelDef = model.models.First();

        // Check that all transitions in the model have corresponding actions
        var actionMap = ModelBasedTester.GetActionMap();
        foreach (var edge in modelDef.edges)
        {
            Assert.Contains(edge.name, actionMap.Keys);
        }

        // Check that all states in the model are valid ApplicationStatus values
        var transitionMap = ModelBasedTester.GetTransitionMap();
        foreach (var vertex in modelDef.vertices)
        {
            // Skip if it's not a valid ApplicationStatus (some vertices might be intermediate)
            if (Enum.TryParse<ApplicationStatus>(vertex.id, out _))
            {
                Assert.Contains(vertex.id, transitionMap.Keys.Select(k => k.ToString()));
            }
        }
    }

    [Fact]
    public void AltWalkerSequences_ReachExpectedStates()
    {
        var sequences = AltWalkerAdapter.GenerateSequences(ApplicationStatus.Started, maxDepth: 10).ToList();

        // Should generate some sequences
        Assert.True(sequences.Count > 0, "AltWalker should generate sequences");

        // Check that sequences contain valid transitions
        var actionMap = ModelBasedTester.GetActionMap();
        foreach (var sequence in sequences)
        {
            foreach (var action in sequence)
            {
                Assert.Contains(action, actionMap.Keys);
            }
        }

        // At least some sequences should reach terminal states
        var terminalSequences = sequences.Where(s =>
            s.Contains("CheckAllVerifications") || // Leads to Approved
            s.Any(step => step.Contains("Failure")) // Leads to Rejected
        ).ToList();

        Assert.True(terminalSequences.Count > 0, "Some sequences should reach terminal states");
    }

    [Fact]
    public void AltWalkerModelBasedTest_Integration()
    {
        // Full integration test using AltWalker-generated sequences
        var sequences = AltWalkerAdapter.GenerateSequences(ApplicationStatus.Started, maxDepth: 15).ToList();

        // Find sequences that go through the full application process
        var completeSequences = sequences.Where(s =>
            s.Contains("SubmitApplication") &&
            s.Any(step => step.Contains("Verify"))
        ).ToList();

        Assert.True(completeSequences.Count > 0, "Should have sequences that include verification steps");

        // Execute a few complete sequences and verify they work
        foreach (var sequence in completeSequences.Take(3))
        {
            var app = new AccountApplication();
            AltWalkerAdapter.ExecuteSequence(app, sequence);

            // Should be in a valid final state
            Assert.True(
                app.Status == ApplicationStatus.Approved ||
                app.Status == ApplicationStatus.Rejected ||
                app.Status == ApplicationStatus.IdVerified ||
                app.Status == ApplicationStatus.AddressVerified ||
                app.Status == ApplicationStatus.CitizenVerified,
                $"Sequence {string.Join(",", sequence)} ended in invalid state: {app.Status}"
            );
        }
    }
}
